services:
  - type: web
    name: doctors-appointments-backend
    env: node
    plan: free
    buildCommand: "cd backend && npm install"
    startCommand: "cd backend && npm run start"
    autoDeploy: true
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
